apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plex-series-scheduler.configMapName" . }}
  labels:
    {{- include "plex-series-scheduler.labels" . | nindent 4 }}
data:
  {{ .Values.configFileName }}: |
    {{- toYaml .Values.config | nindent 4 }}
