{{- if eq .Values.deploymentMethod "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "plex-series-scheduler.fullname" . }}
  labels:
    {{- include "plex-series-scheduler.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  {{- with .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      {{- with .Values.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . }}
      {{- end }}
      {{- with .Values.cronjob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        metadata:
          labels:
            {{- include "plex-series-scheduler.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "plex-series-scheduler.serviceAccountName" . }}
          automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: scheduler
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - -config
                - /config/{{ .Values.configFileName }}
                - -once
                - -metrics-addr
                - ""
              env:
                {{- include "plex-series-scheduler.commonEnv" . | nindent 16 }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              volumeMounts:
                {{- include "plex-series-scheduler.commonVolumeMounts" . | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            {{- include "plex-series-scheduler.commonVolumes" . | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
