{{- if eq .Values.deploymentMethod "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex-series-scheduler.fullname" . }}
  labels:
    {{- include "plex-series-scheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "plex-series-scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plex-series-scheduler.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "plex-series-scheduler.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config
            - /config/{{ .Values.configFileName }}
            - -metrics-addr
            - :{{ .Values.service.port }}
          env:
            {{- include "plex-series-scheduler.commonEnv" . | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- include "plex-series-scheduler.commonVolumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
      volumes:
        {{- include "plex-series-scheduler.commonVolumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
